name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.7'  # minimum julia version
          - '1'    # latest stable 1.x
          - 'nightly'
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        python-version: ['3.9']
        
    steps:
      - uses: actions/checkout@v2

      # Python setup for matplotlib
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Verify Python
        run: python -c "import sys; print(f'Python {sys.version}')"

      - name: Install matplotlib
        run: python -m pip install -U matplotlib

      # Julia setup
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}

      # Caching for faster builds
      - name: Cache Julia artifacts
        uses: actions/cache@v2
        env:
          cache-name: cache-artifacts
        with:
          path: |
            ~/.julia/artifacts
            ~/.julia/compiled
          key: ${{ runner.os }}-julia-${{ matrix.version }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-${{ matrix.version }}-
            ${{ runner.os }}-julia-
            ${{ runner.os }}-

      - name: Cache Julia packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.julia/packages
            ~/.julia/registries
          key: ${{ runner.os }}-julia-pkg-${{ matrix.version }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-julia-pkg-${{ matrix.version }}-
            ${{ runner.os }}-julia-pkg-
            ${{ runner.os }}-

      # Build and test
      - uses: julia-actions/julia-buildpkg@v1
        env:
          PYTHON: python

      - uses: julia-actions/julia-runtest@v1

      - uses: julia-actions/julia-processcoverage@v1

      # Failure notification
      - name: Notify on failure
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "❌ CI failed on ${{ matrix.os }} with Julia ${{ matrix.version }}\n\n" +
                    "See details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            })
